# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: deploy to production

on:
  push:
    paths:
      - "web/**"
      - ".github/workflows/**"
    branches: ["main"]

jobs:
  build:
    runs-on: self-hosted
    # defaults:
    #   run:
    #     working-directory: ./web/client
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js18
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Change directory
        run: |
          cd ./web
          touch config.env
          echo "${{ secrets.PROD_ENV_FILE }}" > config.env
          npm install
      - run: |
          cd ./web/client
          npm install --force
          touch .env
          echo "${{ secrets.FRONT_ENV_FILE }}" > .env

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Use Node.js18
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Deploy to production
        run: |
          npm install -g pm2
          pm2 start react-app
          pm2 start backend
