# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: deploy to production

on:
  push:
    paths:
      - "web/**"
    branches: ["main"]

jobs:
  build:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: ./web/client
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18
        run: cd web/client
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"
      - run: npm ci
      - name: Change directory
        run: |
          cd ./web
          touch config.env
          echo "${{ secrets.PROD_ENV_FILE }}" > config.env
          npm ci
      # - run: |
      #     touch .env
      #     echo "${{ secrets.PROD_ENV_FILE }}" > .env
